<!DOCTYPE HTML>
<HTML>
	<HEAD>
		<TITLE>THE NOODLE BAR | CHECKOUT</TITLE>
		<meta charset="utf-8">
		<link href="css/checkoutstyle.css" rel="stylesheet">
		<STYLE>
		#TABLE,#ADDRESS
		{
		visibility:hidden;
		}
		</STYLE>
		<SCRIPT src="val.js"></SCRIPT>
	<HEAD>
	<BODY>
	<BODY>
		<FORM method="post">
			<PRE>
				<LABEL>FULL NAME</LABEL>
				<INPUT TYPE="TEXT" NAME="C1" ID="NAME" VALUE="" PLACEHOLDER="ENTER YOUR NAME..." REQUIRED>
				
				<LABEL>EMAIL ID</LABEL>
				<INPUT TYPE="EMAIL" NAME="C2" PLACEHOLDER="ENTER YOUR EMAIL..." REQUIRED>
				
				<LABEL>PHONE NUMBER</LABEL>
				<INPUT TYPE="TEXT"  NAME="C3" ID="PHN" VALUE="" PLACEHOLDER="ENTER PHONE NUMBER..." REQUIRED>
				
				<INPUT TYPE="RADIO" NAME="C4" ID="DT1" VALUE="" ONCLICK="val_door();">AT YOUR DOORSTEP
				<INPUT TYPE="RADIO" NAME="C4" ID="DT2" VALUE="" ONCLICK="val_table();">AT THE TABLE
				
				<INPUT TYPE="NUMBER" NAME="C5" ID="TABLE" VALUE="" PLACEHOLDER="ENTER TABLE NUMBER.." REQUIRED>
				
				<TEXTAREA ROWS="5" COLS="20" NAME="C6" ID="ADDRESS" PLACEHOLDER="ENTER YOUR ADDRESS...." MAXLENGTH="150"></TEXTAREA>
				
				<LABEL>CITY</LABEL>
				<SELECT NAME="C7" ID="CITY">
					<OPTION VALUE="T4">KOLKATA</OPTION>
				</SELECT>
				
				<LABEL>PINCODE</LABEL>
				<INPUT TYPE="NUMBER" NAME="C8" ID="PIN" VALUE="7000" PLACEHOLDER="ENTER YOUR NAME..." REQUIRED>

				<INPUT TYPE="SUBMIT" NAME="BTN" ID="BTN_ID" VALUE="SIGN UP">	
			</PRE>
		</FORM>
	</BODY>
</HTML>